language: node_js

install: npm install

jobs:
  include:
    - stage: spec tests ğŸ‘©ğŸ½â€ğŸ’»
      script: npm run test
      node_js: lts/*
    - node_js: node

    - stage: lint âœ¨
      script: npm run lint
      node_js: lts/*


    - stage: release ğŸ‰
      if: branch = master && type != pull_request
      script: npm run semantic-release
      node_js: lts/*

cache:
  directories:
    - node_modules

git:
  depth: 3
